// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgFIy1ltqRhetwMTiafOSvpPSHKthKHCw',
    appId: '1:910214065001:web:e7b09ff8236b1e37902bf8',
    messagingSenderId: '910214065001',
    projectId: 'dainamicauth',
    authDomain: 'dainamicauth.firebaseapp.com',
    storageBucket: 'dainamicauth.appspot.com',
    measurementId: 'G-6B9254W3VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnt_ke88wjMmka0s1_rFQQuebr4l7vHc',
    appId: '1:910214065001:android:6b109d03114276d8902bf8',
    messagingSenderId: '910214065001',
    projectId: 'dainamicauth',
    storageBucket: 'dainamicauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQTaO45sUEv5SSVR19vhzFQ34bdtIZWtw',
    appId: '1:910214065001:ios:d1a6e33fd489ce94902bf8',
    messagingSenderId: '910214065001',
    projectId: 'dainamicauth',
    storageBucket: 'dainamicauth.appspot.com',
    iosBundleId: 'com.app.dainamicauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQTaO45sUEv5SSVR19vhzFQ34bdtIZWtw',
    appId: '1:910214065001:ios:1c3e82cbd552ba48902bf8',
    messagingSenderId: '910214065001',
    projectId: 'dainamicauth',
    storageBucket: 'dainamicauth.appspot.com',
    iosBundleId: 'com.app.dainamicauth.RunnerTests',
  );
}
